### ISSUE TITLE
URL with parameter not hitting privateroute

### ISSUE THREAD

**Issue by yakkalipavan** [Franpastoragusti/oidc-react-app#2]
HI,

I am having issue, I am trying to hit PrivateRoute path with parameter (post/:postid) but it is not redirecting login page. All my code is same as this repository. 
<PrivateRoute path='/post/:postid' component={PostDetailPage} />

I am trying to hit https://locahost/post/123. But it is not redirecting to login page. 

So can you explain me how to handle this with your code build. 

Please let me know if you need any details.

**Comment by Franpastoragusti** [comment]
can you give me access to this repo to be checked?? if you have created a private route with this url it should work if you have defined well in the routes. the private route implemented should be like this
<PrivateRoute
            path="/post/:post"
            component={PostPage}
/>
and in this way by props.params.post you should be able to access if you are logged in or redirected to the login page
